// This file was generated by counterfeiter
package translationfakes

import (
	"sync"

	setdatamodel "github.com/jwfriese/workouttrackerapi/lifts/sets/datamodel"
	"github.com/jwfriese/workouttrackerapi/lifts/sets/translation"
)

type FakeSetsCreateRequestTranslator struct {
	TranslateStub        func(requestJSON []byte) (*setdatamodel.Set, error)
	translateMutex       sync.RWMutex
	translateArgsForCall []struct {
		requestJSON []byte
	}
	translateReturns struct {
		result1 *setdatamodel.Set
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSetsCreateRequestTranslator) Translate(requestJSON []byte) (*setdatamodel.Set, error) {
	var requestJSONCopy []byte
	if requestJSON != nil {
		requestJSONCopy = make([]byte, len(requestJSON))
		copy(requestJSONCopy, requestJSON)
	}
	fake.translateMutex.Lock()
	fake.translateArgsForCall = append(fake.translateArgsForCall, struct {
		requestJSON []byte
	}{requestJSONCopy})
	fake.recordInvocation("Translate", []interface{}{requestJSONCopy})
	fake.translateMutex.Unlock()
	if fake.TranslateStub != nil {
		return fake.TranslateStub(requestJSON)
	} else {
		return fake.translateReturns.result1, fake.translateReturns.result2
	}
}

func (fake *FakeSetsCreateRequestTranslator) TranslateCallCount() int {
	fake.translateMutex.RLock()
	defer fake.translateMutex.RUnlock()
	return len(fake.translateArgsForCall)
}

func (fake *FakeSetsCreateRequestTranslator) TranslateArgsForCall(i int) []byte {
	fake.translateMutex.RLock()
	defer fake.translateMutex.RUnlock()
	return fake.translateArgsForCall[i].requestJSON
}

func (fake *FakeSetsCreateRequestTranslator) TranslateReturns(result1 *setdatamodel.Set, result2 error) {
	fake.TranslateStub = nil
	fake.translateReturns = struct {
		result1 *setdatamodel.Set
		result2 error
	}{result1, result2}
}

func (fake *FakeSetsCreateRequestTranslator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.translateMutex.RLock()
	defer fake.translateMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeSetsCreateRequestTranslator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ translation.SetsCreateRequestTranslator = new(FakeSetsCreateRequestTranslator)
