#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR

psql -lt | cut -d \| -f 1 | grep workout_tracker_integration_test >/dev/null
UNIT_TEST_DATABASE_EXISTS=$?

if [ $UNIT_TEST_DATABASE_EXISTS -eq 0 ]; then
        echo -e "\nIntegration testing database exists. Cleaning...\n"
        psql -d postgres -U postgres -c 'DROP DATABASE workout_tracker_integration_test' 
fi

createdb -U postgres workout_tracker_integration_test
CREATE_SUCCESSFUL=$?
if [ $CREATE_SUCCESSFUL -eq 0 ]; then
        echo -e "Integration testing database created\n"
else
        echo -e "Failed to create integration testing database\n"
        exit
fi

echo -e "\nInitializing integration test database...\n"

psql -d workout_tracker_integration_test -U postgres -f initialize_workouts.sql
psql -d workout_tracker_integration_test -U postgres -f initialize_lifts.sql

