// This file was generated by counterfeiter
package repositoryfakes

import (
	"sync"

	liftdatamodel "github.com/jwfriese/workouttrackerapi/lifts/datamodel"
	"github.com/jwfriese/workouttrackerapi/lifts/repository"
)

type FakeLiftRepository struct {
	AllStub        func() []*liftdatamodel.Lift
	allMutex       sync.RWMutex
	allArgsForCall []struct{}
	allReturns     struct {
		result1 []*liftdatamodel.Lift
	}
	GetByIdStub        func(id int) (*liftdatamodel.Lift, error)
	getByIdMutex       sync.RWMutex
	getByIdArgsForCall []struct {
		id int
	}
	getByIdReturns struct {
		result1 *liftdatamodel.Lift
		result2 error
	}
	InsertStub        func(*liftdatamodel.Lift) (int, error)
	insertMutex       sync.RWMutex
	insertArgsForCall []struct {
		arg1 *liftdatamodel.Lift
	}
	insertReturns struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLiftRepository) All() []*liftdatamodel.Lift {
	fake.allMutex.Lock()
	fake.allArgsForCall = append(fake.allArgsForCall, struct{}{})
	fake.recordInvocation("All", []interface{}{})
	fake.allMutex.Unlock()
	if fake.AllStub != nil {
		return fake.AllStub()
	} else {
		return fake.allReturns.result1
	}
}

func (fake *FakeLiftRepository) AllCallCount() int {
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	return len(fake.allArgsForCall)
}

func (fake *FakeLiftRepository) AllReturns(result1 []*liftdatamodel.Lift) {
	fake.AllStub = nil
	fake.allReturns = struct {
		result1 []*liftdatamodel.Lift
	}{result1}
}

func (fake *FakeLiftRepository) GetById(id int) (*liftdatamodel.Lift, error) {
	fake.getByIdMutex.Lock()
	fake.getByIdArgsForCall = append(fake.getByIdArgsForCall, struct {
		id int
	}{id})
	fake.recordInvocation("GetById", []interface{}{id})
	fake.getByIdMutex.Unlock()
	if fake.GetByIdStub != nil {
		return fake.GetByIdStub(id)
	} else {
		return fake.getByIdReturns.result1, fake.getByIdReturns.result2
	}
}

func (fake *FakeLiftRepository) GetByIdCallCount() int {
	fake.getByIdMutex.RLock()
	defer fake.getByIdMutex.RUnlock()
	return len(fake.getByIdArgsForCall)
}

func (fake *FakeLiftRepository) GetByIdArgsForCall(i int) int {
	fake.getByIdMutex.RLock()
	defer fake.getByIdMutex.RUnlock()
	return fake.getByIdArgsForCall[i].id
}

func (fake *FakeLiftRepository) GetByIdReturns(result1 *liftdatamodel.Lift, result2 error) {
	fake.GetByIdStub = nil
	fake.getByIdReturns = struct {
		result1 *liftdatamodel.Lift
		result2 error
	}{result1, result2}
}

func (fake *FakeLiftRepository) Insert(arg1 *liftdatamodel.Lift) (int, error) {
	fake.insertMutex.Lock()
	fake.insertArgsForCall = append(fake.insertArgsForCall, struct {
		arg1 *liftdatamodel.Lift
	}{arg1})
	fake.recordInvocation("Insert", []interface{}{arg1})
	fake.insertMutex.Unlock()
	if fake.InsertStub != nil {
		return fake.InsertStub(arg1)
	} else {
		return fake.insertReturns.result1, fake.insertReturns.result2
	}
}

func (fake *FakeLiftRepository) InsertCallCount() int {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	return len(fake.insertArgsForCall)
}

func (fake *FakeLiftRepository) InsertArgsForCall(i int) *liftdatamodel.Lift {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	return fake.insertArgsForCall[i].arg1
}

func (fake *FakeLiftRepository) InsertReturns(result1 int, result2 error) {
	fake.InsertStub = nil
	fake.insertReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeLiftRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.allMutex.RLock()
	defer fake.allMutex.RUnlock()
	fake.getByIdMutex.RLock()
	defer fake.getByIdMutex.RUnlock()
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeLiftRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.LiftRepository = new(FakeLiftRepository)
